FROM docker.m.daocloud.io/library/eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY backend/simple-website-backend-1.0.0.jar app.jar
RUN mkdir -p /etc/eastSouth/backend/upload
EXPOSE 8084
ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-jar", "app.jar", \
  "--spring.datasource.url=jdbc:mysql://mysql:3306/simple_website?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true", \
  "--spring.datasource.username=root", \
  "--spring.datasource.password=root123456"]
